version: "3.8"

services:
    nginx:
        image: "nginx:stable-alpine"
        ports:
            - "8000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/laravel
        depends_on:
            - mysql
            - php
    php:
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel
            - ./dockerfiles/configs/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        environment:
            PHP_IDE_CONFIG: serverName=Docker
    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        env_file:
            - env/mysql.env
        volumes:
            - db_data:/var/lib/mysql
    phpmyadmin:
        depends_on:
            -   mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_HOST = host.docker.internal
            - PMA_PORT = 3306
    composer:
        build:
            context: dockerfiles
            dockerfile: composer.Dockerfile
        volumes:
            - ./src:/var/www/laravel
    artisan:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel
        entrypoint: ["php", "/var/www/laravel/artisan"]
    clickhouse:
        image: yandex/clickhouse-server
        ports:
            - "8123:8123"
            - "9000:9000"
        volumes:
            - ./clickhouse-data:/var/lib/clickhouse
volumes:
    db_data: